# -*- coding: utf-8 -*-
"""HOMEWORK_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16tG1xRTnbX-_ak-Iip4pGFLiQM1kj6JU
"""

#1.	Tensor Manipulations & Reshaping
import tensorflow as tf

# Step 1: Create a random tensor of shape (4, 6)
tensor = tf.random.uniform((4, 6))

# Step 2: Find its rank and shape
rank = tf.rank(tensor).numpy()
shape = tensor.shape
print(f"Original Tensor Rank: {rank}")
print(f"Original Tensor Shape: {shape}")

# Step 3: Reshape to (2, 3, 4) and Transpose to (3, 2, 4)
reshaped_tensor = tf.reshape(tensor, (2, 3, 4))
transposed_tensor = tf.transpose(reshaped_tensor, perm=[1, 0, 2])
print(f"Reshaped Tensor Shape: {reshaped_tensor.shape}")
print(f"Transposed Tensor Shape: {transposed_tensor.shape}")

# Step 4: Broadcasting a smaller tensor (1, 4) to match a larger tensor
small_tensor = tf.random.uniform((1, 4))
broadcasted_tensor = small_tensor + tf.zeros((3, 2, 4))  # Expanding dimensions implicitly
result_tensor = transposed_tensor + broadcasted_tensor
print(f"Resultant Tensor Shape after Broadcasting and Addition: {result_tensor.shape}")

# Step 5: Explanation of Broadcasting
explanation = """
Broadcasting in TensorFlow works by automatically expanding the smaller tensor's dimensions
so that they match the shape of the larger tensor. In this case, the smaller tensor (1, 4)
was expanded to (3, 2, 4) to match the transposed tensor before performing element-wise addition.
"""
print(explanation)

# 2.	Loss Functions & Hyperparameter Tuning
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

# Step 1: Define true values and model predictions
y_true = tf.constant([1.0, 0.0, 1.0, 1.0])
y_pred1 = tf.constant([0.9, 0.1, 0.8, 0.95])  # Initial predictions
y_pred2 = tf.constant([0.8, 0.2, 0.7, 0.85])  # Slightly modified predictions

# Step 2: Compute Mean Squared Error (MSE) and Categorical Cross-Entropy (CCE) losses
mse_loss1 = tf.keras.losses.MeanSquaredError()(y_true, y_pred1).numpy()
mse_loss2 = tf.keras.losses.MeanSquaredError()(y_true, y_pred2).numpy()

cce_loss1 = tf.keras.losses.CategoricalCrossentropy()(y_true, y_pred1).numpy()
cce_loss2 = tf.keras.losses.CategoricalCrossentropy()(y_true, y_pred2).numpy()

print(f"MSE Loss (Prediction 1): {mse_loss1}")
print(f"MSE Loss (Prediction 2): {mse_loss2}")
print(f"CCE Loss (Prediction 1): {cce_loss1}")
print(f"CCE Loss (Prediction 2): {cce_loss2}")

# Step 4: Plot loss function values using Matplotlib
labels = ['MSE (Pred 1)', 'MSE (Pred 2)', 'CCE (Pred 1)', 'CCE (Pred 2)']
loss_values = [mse_loss1, mse_loss2, cce_loss1, cce_loss2]

plt.figure(figsize=(8, 5))
plt.bar(labels, loss_values, color=['blue', 'cyan', 'red', 'orange'])
plt.ylabel('Loss Value')
plt.title('Comparison of MSE and CCE Losses')
plt.show()

# Step 5: Explanation of Broadcasting
explanation = """
Broadcasting in TensorFlow works by automatically expanding the smaller tensor's dimensions
so that they match the shape of the larger tensor. In this case, the smaller tensor (1, 4)
was expanded to (3, 2, 4) to match the transposed tensor before performing element-wise addition.
"""
print(explanation)

#3.	Train a Model with Different Optimizers
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt

# Step 1: Define true values and model predictions
y_true = tf.constant([1.0, 0.0, 1.0, 1.0])
y_pred1 = tf.constant([0.9, 0.1, 0.8, 0.95])  # Initial predictions
y_pred2 = tf.constant([0.8, 0.2, 0.7, 0.85])  # Slightly modified predictions

# Step 2: Compute Mean Squared Error (MSE) and Categorical Cross-Entropy (CCE) losses
mse_loss1 = tf.keras.losses.MeanSquaredError()(y_true, y_pred1).numpy()
mse_loss2 = tf.keras.losses.MeanSquaredError()(y_true, y_pred2).numpy()

cce_loss1 = tf.keras.losses.CategoricalCrossentropy()(y_true, y_pred1).numpy()
cce_loss2 = tf.keras.losses.CategoricalCrossentropy()(y_true, y_pred2).numpy()

print(f"MSE Loss (Prediction 1): {mse_loss1}")
print(f"MSE Loss (Prediction 2): {mse_loss2}")
print(f"CCE Loss (Prediction 1): {cce_loss1}")
print(f"CCE Loss (Prediction 2): {cce_loss2}")

# Step 4: Plot loss function values using Matplotlib
labels = ['MSE (Pred 1)', 'MSE (Pred 2)', 'CCE (Pred 1)', 'CCE (Pred 2)']
loss_values = [mse_loss1, mse_loss2, cce_loss1, cce_loss2]

plt.figure(figsize=(8, 5))
plt.bar(labels, loss_values, color=['blue', 'cyan', 'red', 'orange'])
plt.ylabel('Loss Value')
plt.title('Comparison of MSE and CCE Losses')
plt.show()

# Step 5: Train MNIST Model with Adam & SGD
# Load MNIST dataset
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0  # Normalize

# Define model architecture
def create_model():
    model = tf.keras.models.Sequential([
        tf.keras.layers.Flatten(input_shape=(28, 28)),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dense(10, activation='softmax')
    ])
    return model

# Train model with Adam optimizer
model_adam = create_model()
model_adam.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
history_adam = model_adam.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=5)

# Train model with SGD optimizer
model_sgd = create_model()
model_sgd.compile(optimizer='sgd', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
history_sgd = model_sgd.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=5)

# Compare accuracy trends
plt.figure(figsize=(8, 5))
plt.plot(history_adam.history['val_accuracy'], label='Adam')
plt.plot(history_sgd.history['val_accuracy'], label='SGD')
plt.xlabel('Epoch')
plt.ylabel('Validation Accuracy')
plt.title('Adam vs. SGD Performance')
plt.legend()
plt.show()

# Step 6: Explanation of Broadcasting
explanation = """
Broadcasting in TensorFlow works by automatically expanding the smaller tensor's dimensions
so that they match the shape of the larger tensor. In this case, the smaller tensor (1, 4)
was expanded to (3, 2, 4) to match the transposed tensor before performing element-wise addition.
"""
print(explanation)

#4.	Train a Neural Network and Log to TensorBoard
import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
import datetime

# Step 1: Define true values and model predictions
y_true = tf.constant([1.0, 0.0, 1.0, 1.0])
y_pred1 = tf.constant([0.9, 0.1, 0.8, 0.95])  # Initial predictions
y_pred2 = tf.constant([0.8, 0.2, 0.7, 0.85])  # Slightly modified predictions

# Step 2: Compute Mean Squared Error (MSE) and Categorical Cross-Entropy (CCE) losses
mse_loss1 = tf.keras.losses.MeanSquaredError()(y_true, y_pred1).numpy()
mse_loss2 = tf.keras.losses.MeanSquaredError()(y_true, y_pred2).numpy()

cce_loss1 = tf.keras.losses.CategoricalCrossentropy()(y_true, y_pred1).numpy()
cce_loss2 = tf.keras.losses.CategoricalCrossentropy()(y_true, y_pred2).numpy()

print(f"MSE Loss (Prediction 1): {mse_loss1}")
print(f"MSE Loss (Prediction 2): {mse_loss2}")
print(f"CCE Loss (Prediction 1): {cce_loss1}")
print(f"CCE Loss (Prediction 2): {cce_loss2}")

# Step 4: Plot loss function values using Matplotlib
labels = ['MSE (Pred 1)', 'MSE (Pred 2)', 'CCE (Pred 1)', 'CCE (Pred 2)']
loss_values = [mse_loss1, mse_loss2, cce_loss1, cce_loss2]

plt.figure(figsize=(8, 5))
plt.bar(labels, loss_values, color=['blue', 'cyan', 'red', 'orange'])
plt.ylabel('Loss Value')
plt.title('Comparison of MSE and CCE Losses')
plt.show()

# Step 5: Train MNIST Model with Adam & SGD
# Load MNIST dataset
mnist = tf.keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0  # Normalize

# Define model architecture
def create_model():
    model = tf.keras.models.Sequential([
        tf.keras.layers.Flatten(input_shape=(28, 28)),
        tf.keras.layers.Dense(128, activation='relu'),
        tf.keras.layers.Dense(10, activation='softmax')
    ])
    return model

# Train model with Adam optimizer
model_adam = create_model()
model_adam.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
history_adam = model_adam.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=5)

# Train model with SGD optimizer
model_sgd = create_model()
model_sgd.compile(optimizer='sgd', loss='sparse_categorical_crossentropy', metrics=['accuracy'])
history_sgd = model_sgd.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=5)

# Compare accuracy trends
plt.figure(figsize=(8, 5))
plt.plot(history_adam.history['val_accuracy'], label='Adam')
plt.plot(history_sgd.history['val_accuracy'], label='SGD')
plt.xlabel('Epoch')
plt.ylabel('Validation Accuracy')
plt.title('Adam vs. SGD Performance')
plt.legend()
plt.show()

# Step 6: Train a Neural Network and Log to TensorBoard
log_dir = "logs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = tf.keras.callbacks.TensorBoard(log_dir=log_dir, histogram_freq=1)

model_tb = create_model()
model_tb.compile(optimizer='adam', loss='sparse_categorical_crossentropy', metrics=['accuracy'])

model_tb.fit(x_train, y_train, validation_data=(x_test, y_test), epochs=5, callbacks=[tensorboard_callback])

print("Training logs saved in:", log_dir)

# Step 7: Explanation of Broadcasting
explanation = """
Broadcasting in TensorFlow works by automatically expanding the smaller tensor's dimensions
so that they match the shape of the larger tensor. In this case, the smaller tensor (1, 4)
was expanded to (3, 2, 4) to match the transposed tensor before performing element-wise addition.
"""
print(explanation)

"""Answers to Your Questions:
What patterns do you observe in the training and validation accuracy curves?

Typically, the training accuracy increases faster than validation accuracy.
Adam tends to reach a higher validation accuracy in fewer epochs compared to SGD.
SGD shows a slower, steadier improvement, sometimes converging to a lower accuracy than Adam.
If overfitting occurs, training accuracy remains high while validation accuracy plateaus or decreases.
How can you use TensorBoard to detect overfitting?

TensorBoard allows visualization of training vs. validation accuracy and loss over epochs.
If validation loss increases while training loss continues to decrease, it indicates overfitting.
Large gaps between training and validation accuracy also signal overfitting.
Monitoring weight distributions and activation histograms in TensorBoard can provide additional insights.
What happens when you increase the number of epochs?

Initially, both training and validation accuracy improve.
After a certain point, validation accuracy may plateau or decline while training accuracy continues increasing, showing overfitting.
The loss curve can indicate diminishing returns, where further training does not significantly improve performance.
If using SGD, increasing epochs might be necessary to reach optimal performance, while Adam converges faster.

"""

